POST https://node-iniciante.onrender.com/videos
Content-Type: application/json / //informa o tipo de conteudo a ser enviado no caso json

{
    "title": "MANOEL BRISOLA",
    "description": "este é o priemiro video MARIA",
    "duration": "160"
}

###
GET https://node-iniciante.onrender.com/videos

### 
GET https://node-iniciante.onrender.com/videos?search=JOAO

###
PUT https://node-iniciante.onrender.com/videos/30b4a5bc-6929-4de8-91e7-b95f1b4136bc
Content-Type: application/json

{
    "title": "LUCAS 01",
    "description": "LUCAS",
    "duration": "240"
  }

###
DELETE https://node-iniciante.onrender.com/videos/
